### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by syn1de** [abdulrahmanDev1/dotfiles#1]
`fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Error: The following formula cannot be installed from bottle and must be\nbuilt from source.\n  sesh\nInstall Clang or run `brew install gcc`."}`

tried manually installing

**Comment by abdulrahmanDev1** [comment]
This was an issue with how [sesh](https://github.com/joshmedeski/sesh) is being installed, I removed it from the list 5ac71fe so it should be good to go now, please refer to the [sesh](https://github.com/joshmedeski/sesh) repo for installation if you need it.

**Comment by syn1de** [comment]
thankyou

**Comment by syn1de** [comment]
`fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/flatpak install --system --noninteractive flathub com.obsproject.Studio org.videolan.VLC org.tenacityaudio.Tenacity md.obsidian.Obsidian org.gimp.GIMP org.gnome.meld org.sqlitebrowser.sqlitebrowser us.zoom.Zoom org.gnome.World.PikaBackup com.mattjakeman.ExtensionManager org.freedesktop.Platform nl.hjdskes.gcolor3", "msg": "error: No ref chosen to resolve matches for ‘org.freedesktop.Platform’", "rc": 1, "stderr": "error: No ref chosen to resolve matches for ‘org.freedesktop.Platform’\n", "stderr_lines": ["error: No ref chosen to resolve matches for ‘org.freedesktop.Platform’"], "stdout": "Similar refs found for ‘org.freedesktop.Platform’ in remote ‘flathub’ (system):\n\n   1) runtime/org.freedesktop.Platform/x86_64/19.08\n   2) runtime/org.freedesktop.Platform/x86_64/1.6\n   3) runtime/org.freedesktop.Platform/x86_64/20.08\n   4) runtime/org.freedesktop.Platform/x86_64/21.08\n   5) runtime/org.freedesktop.Platform/x86_64/22.08\n   6) runtime/org.freedesktop.Platform/x86_64/23.08\n   7) runtime/org.freedesktop.Platform/x86_64/18.08\n\nWhich do you want to use (0 to abort)? [0-7]: 0\n", "stdout_lines": ["Similar refs found for ‘org.freedesktop.Platform’ in remote ‘flathub’ (system):", "", "   1) runtime/org.freedesktop.Platform/x86_64/19.08", "   2) runtime/org.freedesktop.Platform/x86_64/1.6", "   3) runtime/org.freedesktop.Platform/x86_64/20.08", "   4) runtime/org.freedesktop.Platform/x86_64/21.08", "   5) runtime/org.freedesktop.Platform/x86_64/22.08", "   6) runtime/org.freedesktop.Platform/x86_64/23.08", "   7) runtime/org.freedesktop.Platform/x86_64/18.08", "", "Which do you want to use (0 to abort)? [0-7]: 0"]}
`

seems like a flatpak error

**Comment by abdulrahmanDev1** [comment]
The problem was it needed a specific [Free Desktop Platform](https://www.freedesktop.org/wiki/)  version to download, for me it was already downloaded so I didn't face this issue, I set the latest version "23.08" to be used c222eaf so I think it should work for you now, please try again and confirm if its working.

**Comment by syn1de** [comment]
download free desktop platform worked but , `fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cat", "../.finished"], "delta": "0:00:00.002242", "end": "2024-07-13 11:20:57.148905", "msg": "non-zero return code", "rc": 1, "start": "2024-07-13 11:20:57.146663", "stderr": "cat: ../.finished: No such file or directory", "stderr_lines": ["cat: ../.finished: No such file or directory"], "stdout": "", "stdout_lines": []}
`

**Comment by abdulrahmanDev1** [comment]
Dont worry about that its a message after its finished, its done it job :)

**Comment by syn1de** [comment]
oh got it  :D , can you please add in readme to install golang beforehand because sesh gives error if go is not installed 
` sudo dnf install golang`
`brew install joshmedeski/sesh/sesh OR go install github.com/joshmedeski/sesh@latest`

**Comment by abdulrahmanDev1** [comment]
sesh is not my project it's [Josh Medeski](https://github.com/joshmedeski)'s so I don't have control over it :)
I wasn't using go when I made this config but I am now so I'll add it to the script anyway.

**Comment by syn1de** [comment]
:) 
 👍

**Comment by syn1de** [comment]
hi i wanted to use nvim 
`image.nvim: magick rock not found, please install it and restart your editor. Error: "module 'magick' not found:\n\tno field package.preload['magick']\ncache_loader: module m
agick not found\ncache_loader_lib: module magick not found\n\tno file './magick.lua'\n\tno file '/usr/share/luajit-2.1/magick.lua'\n\tno file '/usr/local/share/lua/5.1/magick
.lua'\n\tno file '/usr/local/share/lua/5.1/magick/init.lua'\n\tno file '/usr/share/lua/5.1/magick.lua'\n\tno file '/usr/share/lua/5.1/magick/init.lua'\n\tno file '/home/zxc/.
luarocks/share/lua/5.1/magick/init.lua'\n\tno file '/home/zxc/.luarocks/share/lua/5.1/magick.lua'\n\tno file '/home/zxc/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/
5.1/magick.lua'\n\tno file '/home/zxc/.local/share/nvim/lazy-rocks/telescope.nvim/share/lua/5.1/magick/init.lua'\n\tno file './magick.so'\n\tno file '/usr/local/lib/lua/5.1/m
agick.so'\n\tno file '/usr/lib64/lua/5.1/magick.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'\n\tno file '/home/zxc/.local/share/nvim/lazy-rocks/telescope.nvim/lib/lua/5
.1/magick.so'"    `

i guess it is discontinued
